<?php

namespace Flowcode\SocialHubBundle\Repository;

/**
 * UserSocialAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSocialAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
