services:


    # providers start
    socialhub_provider_facebook:
        class: Flowcode\SocialHubBundle\Model\FacebookSocialProvider
        arguments: ['@service_container']

    socialhub_provider_twitter:
        class: Flowcode\SocialHubBundle\Model\TwitterSocialProvider
        arguments: ['@service_container']

    # providers end.


    flowcode.socialhub.listplugins_eventsubscriber:
        class: Flowcode\SocialHubBundle\Event\ListPluginsSubscriber
        arguments: ['@router', '@translator']
        tags:
            - { name: kernel.event_subscriber }

    socialhub.repository.socialnetwork:
            class: Doctrine\ORM\EntityRepository
            factory_service: doctrine.orm.default_entity_manager
            factory_method: getRepository
            arguments:
                - Flowcode\SocialHubBundle\Entity\SocialNetwork

    socialhub.service.socialnetwork:
        class: Flowcode\SocialHubBundle\Service\SocialNetworkService
        arguments: ['@service_container','@socialhub.repository.socialnetwork']