services:


    # providers start
    socialhub_provider_facebook:
        class: Flowcode\SocialHubBundle\Model\FacebookSocialProvider
        arguments: ['@service_container']

    socialhub_provider_twitter:
        class: Flowcode\SocialHubBundle\Model\TwitterSocialProvider
        arguments: ['@service_container']

    # providers end.


    flowcode.socialhub.listplugins_eventsubscriber:
        class: Flowcode\SocialHubBundle\Event\ListPluginsSubscriber
        arguments: ['@router', '@translator']
        tags:
            - { name: kernel.event_subscriber }
                
    socialhub.service.socialnetwork:
        class: Flowcode\SocialHubBundle\Service\SocialNetworkService
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@service_container"
    
    socialhub.service.usersocialaccount:
        class: Flowcode\SocialHubBundle\Service\UserSocialAccountService
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@service_container"
          
    socialhub.service.socialprovider:
        class: Flowcode\SocialHubBundle\Service\SocialProviderService
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@service_container"
          